### ISSUE TITLE
Cannot Drag & Drop onto deck from Library. 

### ISSUE THREAD

**Issue by ngoiyaeric** [mixxxdj/mixxx#12987]
### Bug Description

Is this something that was not implemented? I can only drag onto the main playback channel at the top when there is nothing else playing. I suppose its only natural to be able to drag into one of the empty decks to load the audio. 

### Version

2.4

### OS

mac os intel

**Comment by JosepMaJAZ** [comment]
If a deck is playing, there is a setting enabled by default that prevent loading another track onto it.

Other than that  yes, drag&drop (from the library) onto the decks should work.
About Drag&drop from the system file explorer  not sure if that works everywhere, or at all.

There were some problems not sure if with 2.2 or 2.3 with macOS, but those were solved.

**Comment by ngoiyaeric** [comment]
Yea just updated from 2.4 to 2.5. Issue resolved.

**Comment by ronso0** [comment]
@ngoiyaeric When you're starting to use Mixxx make sure you check the manual https://manual.mixxx.org/latest and take a look at the Preferences. The manual has chapters for the more complex/important preferences pages as well as advanced topics re usage of Mixxx.

**Comment by ngoiyaeric** [comment]
I still have an issue when the track on the deck is paused & I want to add a track. Is there a stop rather than pause button.
