### ISSUE TITLE
Missing Rekordbox Playlists on USB Import

### ISSUE THREAD

**Issue by AilaScott** [mixxxdj/mixxx#13309]
### Bug Description

Tried importing playlists from rekordbox 6.8.4 and some playlists were populating in mixxx while others weren't.  Playlists would show up but have no tracks.  Playlist with tracks don't seem to be missing any.

### Version

2.4.1

### OS

Windows 11

**Comment by acolombier** [comment]
Hi @AilaScott,

I believe this is has been solved by @Swiftb0y in #13293 and will be release in version `2.4.2`

**Comment by Swiftb0y** [comment]
And/or 2.5(-beta). If this is still a problem, feel free to reopen this issue. Thank you.

**Comment by 0xsuk** [comment]
I think this is crate-digger's problem. I used crate digger library directly in my hobby code base and observing the same issue. It has to do with the reversing machinery of rekordbox data in the library.

**Comment by Swiftb0y** [comment]
yeah, very possible. The format definitely needs more reverse-engineering work.

**Comment by AilaScott** [comment]
@Swiftb0y @acolombier Still an issue and I've had the same one in both 2.5.0 and 2.5.1.  Could one of y'all re-open the issue?

**Comment by Swiftb0y** [comment]
Thanks for reraising the issue. Unfortunately nobody is working on this right now.

**Comment by AilaScott** [comment]
Ah, I hope someone does soon.   Unreliable RB transfer is one of the few things keeping me from dailying linux.  I'd love to use mixxx full time but I play CDJ gigs quite a bit so I'm stuck using RB for my main library :(

**Comment by Swiftb0y** [comment]
This may be fixed by #15745
